- name: Check mandatory variables
  fail:
    msg: "{{ item }} was not defined!"
  when: vars[item] is undefined or vars[item] == ''
  loop:
    - cluster_name
    - component_name

- set_fact:
    kubeconfig_path: "{{ playbook_dir}}/k8s_components_kubeconfigs/{{ component_name }}.kubeconfig"

- name: Set cluster for kubectl
  command: "kubectl config set-cluster {{ cluster_name }} --certificate-authority={{ playbook_dir }}/ca_tls/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig={{ kubeconfig_path }}"

- name: Set credentials for kubectl
  command: "kubectl config set-credentials system:{{ component_name }} --client-certificate={{ playbook_dir }}/ca_tls/master/{{ component_name }}.pem --client-key={{ playbook_dir }}/ca_tls/master/{{ component_name }}-key.pem --embed-certs=true --kubeconfig={{ kubeconfig_path }}"

- name: Set context for kubelet kubeconfig
  command: "kubectl config set-context default --cluster={{ cluster_name }} --user=system:{{ component_name }} --kubeconfig={{ kubeconfig_path }}"

- name: Use context
  command: "kubectl config use-context default --kubeconfig={{ kubeconfig_path }}"