# TODO: Merge this with prepare_kubelet_kubeconfig.yaml
- name: Check mandatory variables
  fail:
    msg: "{{ item }} was not defined!"
  when: vars[item] is undefined or vars[item] == ''
  loop:
    - masters_frontend_lb
    - cluster_name

- set_fact:
    kubeconfig_path: "{{ playbook_dir}}/k8s_components_kubeconfigs/kube-proxy.kubeconfig"

- name: Set cluster for kubectl
  command: "kubectl config set-cluster {{ cluster_name }} --certificate-authority={{playbook_dir}}/ca_tls/ca.pem --embed-certs=true --server={{ masters_frontend_lb }} --kubeconfig={{ kubeconfig_path }}"

- name: Set credentials for kubectl
  command: "kubectl config set-credentials system:kube-proxy --client-certificate={{ playbook_dir }}/ca_tls/kubernetes-client.pem --client-key={{ playbook_dir }}/ca_tls/kubernetes-client-key.pem --embed-certs=true --kubeconfig={{ kubeconfig_path }}"

- name: Set context for kubelet kubeconfig
  command: "kubectl config set-context default --cluster={{ cluster_name }} --user=system:kube-proxy --kubeconfig={{ kubeconfig_path }}"

- name: Use context
  command: "kubectl config use-context default --kubeconfig={{ kubeconfig_path }}"