# TODO: Merge this with prepare_kube_proxy_kubeconfig.yaml etc.
- name: Check mandatory variables
  fail:
    msg: "{{ item }} was not defined!"
  when: vars[item] is undefined or vars[item] == ''
  loop:
    - k8s_public_host
    - cluster_name

- set_fact:
    kubeconfig_path: "{{ playbook_dir}}/k8s_components_kubeconfigs/admin.kubeconfig"

- name: Set cluster for kubelet kubeconfig
  command: kubectl config set-cluster {{ cluster_name }} --certificate-authority=ca_tls/ca.pem --embed-certs=true --server=https://{{ k8s_public_host }}:443 --kubeconfig={{kubeconfig_path}}

- name: Set credentials for kubelet kubeconfig
  command: kubectl config set-credentials admin --client-certificate=ca_tls/admin.pem --client-key=ca_tls/admin-key.pem --embed-certs=true --kubeconfig={{kubeconfig_path}}

- name: Set context for kubelet kubeconfig
  command: kubectl config set-context default --cluster={{ cluster_name }} --user=admin --kubeconfig={{kubeconfig_path}}

- name: Use context
  command: kubectl config use-context default --kubeconfig={{kubeconfig_path}}