# TODO: Merge this with prepare_kube_proxy_kubeconfig.yaml
- name: Check mandatory variables
  fail:
    msg: "{{ item }} was not defined!"
  when: vars[item] is undefined or vars[item] == ''
  loop:
    - host_idx
    - masters_frontend_lb
    - cluster_name

- set_fact:
    node_name: "worker-{{ host_idx }}"

- set_fact:
    kubeconfig_path: "{{ playbook_dir}}/k8s_components_kubeconfigs/{{node_name}}.kubeconfig"

- name: Set cluster for kubelet kubeconfig
  command: "kubectl config set-cluster {{ cluster_name }} --certificate-authority={{playbook_dir}}/ca_tls/ca.pem --embed-certs=true --server=https://{{masters_frontend_lb}}:443 --kubeconfig={{ kubeconfig_path }}"

- name: Set credentials for kubelet kubeconfig
  command: "kubectl config set-credentials system:node:{{ node_name }} --client-certificate={{ playbook_dir }}/ca_tls/node/{{ node_name }}.pem --client-key={{ playbook_dir }}/ca_tls/node/{{ node_name }}-key.pem --embed-certs=true --kubeconfig={{ kubeconfig_path }}"

- name: Set context for kubelet kubeconfig
  command: "kubectl config set-context default --cluster={{ cluster_name }} --user=system:node:{{ node_name }} --kubeconfig={{ kubeconfig_path }}"

- name: Use context
  command: "kubectl config use-context default --kubeconfig={{ kubeconfig_path }}"