- hosts: localhost
  gather_facts: no
  tasks:
    - include_vars:
        file: "{{ item }}"
      loop:
        - vars/commons.yaml
        - vars/worker.yaml

#    - name: MOCKING!
#      include_vars:
#        file: vars/mock.yaml
#      tags:
#        - mock
#        - test
    - name: Create The Kube Proxy Client Certificate
      shell: cfssl gencert -ca=../ca.pem -ca-key=../ca-key.pem -config=../ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy
      args:
        chdir: "{{ playbook_dir }}/ca_tls/node"

    - name: Create kubeconfig for kubeproxy (node authorization)
      import_tasks: "{{ playbook_dir }}/k8s_components_kubeconfigs/prepare_kube_proxy_kubeconfig.yaml"

- hosts: worker-nodes
  name: Setup worker nodes
  user: ubuntu
#  gather_facts: no
  tasks:
    - include_vars:
        file: "{{ item }}"
      loop:
        - vars/commons.yaml
        - vars/worker.yaml
      tags:
        - always

    - name: Set host index
      set_fact:
        host_idx: "{{ play_hosts.index(inventory_hostname) }}"
      tags:
        - always

    - name: Check mandatory variables
      fail:
        msg: "{{ item }} was not defined!"
      when: vars[item] is undefined or vars[item] == None
      loop:
        - masters_frontend_lb
      tags:
        - always

    - name: Get/Set current host internal/external ip
      block:
        - set_fact:
            host_external_ip: "{{ hostvars[inventory_hostname].inventory_hostname }}"

        - uri:
            url: http://169.254.169.254/latest/meta-data/local-ipv4
            return_content: yes
          register: host_internal_ip_out

        - set_fact:
            host_internal_ip: "{{ host_internal_ip_out.content | trim }}"

        - debug:
            msg: "Set host_internal_ip: {{ host_internal_ip }}"
      tags:
        - always

    - name: Generate kubelet client certificates
      import_tasks: "{{ playbook_dir }}/ca_tls/node/generate-node-authorizer-certificate.yaml"
      delegate_to: localhost

    - name: Create kubeconfig for kubelet (node authorization)
      import_tasks: "{{ playbook_dir }}/k8s_components_kubeconfigs/prepare_kubelet_kubeconfig.yaml"
      delegate_to: localhost

    - name: Install system dependencies
      when: ansible_facts['distribution'] == "Ubuntu" # ansible_facts['distribution'] is defined (fail when undefined?)
      become: true
      # TODO: async
      block:
        - name: Update apt packages
          apt:
            update_cache: yes
        - name: Install os dependencies
          apt:
            name: "{{ packages }}"
          vars:
            packages:
            - socat
            - conntrack
            - ipset

    - name: Download and Install Worker Binaries
      async: "{{ default_async_timeout }}"
      poll: "{{ default_async_poll }}"
      get_url: url={{ item.value }} dest=~/
      with_dict: "{{ worker_resources }}"

    - name: Create config dirs
      async: "{{ default_async_timeout }}"
      poll: "{{ default_async_poll }}"
      become: true
      file:
        path: "{{ item.value }}"
        state: directory
        #recurse: yes
      with_dict: "{{ worker_config_dirs }}"

    - command: mv runc.amd64 runc
      ignore_errors: yes

    - name: chmod +x kubectl kube-proxy kubelet runc.amd64 runsc
      file: dest="{{ item }}" mode=+x
      loop:
        - kubectl
        - kube-proxy
        - kubelet
        - runc
        - runsc

    - name: Move worker binaries
      become: true
      command: mv kubectl kube-proxy kubelet runc runsc /usr/local/bin/

    - name: Extract archives
      become: true
      unarchive: src={{ item.src }} dest={{ item.dest }} remote_src=yes
      with_items:
        - { src: "/home/ubuntu/{{ crictl_version }}.tar.gz", dest: "/usr/local/bin/" }
        - { src: "/home/ubuntu/{{ cni_plugins_version }}.tgz", dest: "/opt/cni/bin/" }
        - { src: "/home/ubuntu/{{ containerd_version }}.tar.gz", dest: "/" }

    - name: Set nodes pod cidr
      set_fact:
        node_pod_cidr: "10.200.{{ host_idx }}.0/24"
      tags: [ 'always' ]

    - name: Process bridge network template and send to remote
      become: true
      template:
        src: "{{ playbook_dir }}/k8s_components_configuration/bridge-network.conf"
        dest: /etc/cni/net.d/10-bridge.conf

    - name: Copy loopback net configuration to remote
      become: true
      copy:
        src: "{{ playbook_dir }}/k8s_components_configuration/loopback-network.conf"
        dest: /etc/cni/net.d/99-loopback.conf

    - name: Copy containerd config and service definition to remote
      become: true
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest}}"
      with_items:
        - { src: "{{ playbook_dir }}/k8s_components_configuration/containerd_conf.toml", dest: "/etc/containerd/config.toml" }
        - { src: "{{ playbook_dir }}/service.definitions/containerd.service", dest: "/etc/systemd/system/containerd.service" }

    - name: Copy certs and config files to worker nodes
      become: true
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "{{ playbook_dir }}/ca_tls/ca.pem", dest: "/var/lib/kubernetes/" }
        - { src: "{{ playbook_dir }}/ca_tls/node/worker-{{ host_idx }}.pem", dest: "/var/lib/kubelet/" }
        - { src: "{{ playbook_dir }}/ca_tls/node/worker-{{ host_idx }}-key.pem", dest: "/var/lib/kubelet/" }
        - { src: "{{ playbook_dir }}/k8s_components_kubeconfigs/worker-{{ host_idx }}.kubeconfig", dest: "/var/lib/kubelet/kubeconfig" }

    - name: Template kubelet-config
      become: true
      template:
        src: "{{ playbook_dir }}/k8s_components_configuration/kubelet-config.yaml"
        dest: /var/lib/kubelet/kubelet-config.yaml

    # TODO: Add Kubelet startup flags: --system-reserved=[cpu=100m][,][memory=100Mi][,][ephemeral-storage=1Gi][,][pid=1000] || --system-reserved-cgroup=
    # https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#system-reserved
    - name: Copy kubelet.service to remotes
      become: true
      copy:
        src: "{{ playbook_dir }}/service.definitions/kubelet.service"
        dest: /etc/systemd/system/kubelet.service

    - name: Template kube-proxy-config
      become: true
      template:
        src: "{{ playbook_dir }}/k8s_components_configuration/kube-proxy-config.yaml"
        dest: /var/lib/kube-proxy/kube-proxy-config.yaml

    - name: Copy kube-proxy kubeconfig and service definition
      become: true
      copy:
        src:  "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "{{ playbook_dir }}/service.definitions/kube-proxy.service", dest: /etc/systemd/system/kube-proxy.service }
        - { src: "{{ playbook_dir }}/k8s_components_kubeconfigs/kube-proxy.kubeconfig", dest: /var/lib/kube-proxy/kubeconfig }

    - name: Reload systemd to reread configs
      become: true
      systemd:
        daemon_reload: yes
      tags:
        - start_components

    - name: Enable worker node services
      become: true
      systemd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - containerd
        - kubelet
        - kube-proxy
      tags:
        - start_components

    - name: Start worker node services
      become: true
      systemd:
        name: "{{ item }}"
        state: started
      loop:
        - containerd
        - kubelet
        - kube-proxy
      tags:
        - start_components

      #TODO: validate node components.

    - name: daemon-reload on worker services
      become: true
      systemd:
        name: "{{ item }}"
        daemon_reload: true
      loop:
        - containerd
        - kubelet
        - kube-proxy
      tags: [ 'restart_components', 'never' ]

    - name: Restart worker services
      become: true
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - containerd
        - kubelet
        - kube-proxy
      tags: [ 'restart_components', 'never' ]

    - name: Create pod network routes block
      tags: [ 'pnr' ]
      block:
      - name: Get aws instance id
        uri:
          url: http://169.254.169.254/latest/meta-data/instance-id
          return_content: yes
        register: instance_id_res

      - set_fact:
          instance_id: "{{ instance_id_res.content | trim }}"

      - name: Provision pod network routes
        when: (network_plugin is defined) and (network_plugin == 'cni')
        command: aws ec2 create-route --route-table-id {{ route_table_id }} --destination-cidr-block {{ node_pod_cidr }} --instance-id {{ instance_id }}
        delegate_to: localhost