AWSTemplateFormatVersion: '2010-09-09'
Description: "Worker EC2 provisioning for k8s cluster"
Resources:
  K8sWorker1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: 'eu-west-2b' # TODO: extract to vars with appropriate subnet (SubnetId)
#      Affinity: 'default' # Check what it the default value
      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            VolumeSize: 15 # in GB
      DisableApiTermination: false # this is the default
      ImageId: 'ami-0b0a60c0a2bd40612'
      InstanceInitiatedShutdownBehavior: 'stop'
      InstanceType: 't2.micro'
      KeyName: 'k8s-operations'
      Monitoring: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          PrivateIpAddress: '10.0.1.5'
          SubnetId: 'subnet-0adff0a2cc48f0f33' # TODO: extract to vars with appropriate AvailabilityZone
          DeviceIndex: '0'
          Description: 'Primary network interface'
          GroupSet:
            - 'sg-074c143d0f082afe6' # k8s-worker-internal (worker)
            - 'sg-0563033eb08ea547e' # k8s-worker-external (worker)
      Tags:
        - Key: node-type
          Value: compute
        - Key: Name
          Value: k8s-worker

  K8sWorker2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: 'eu-west-2a' # TODO: extract to vars with appropriate subnet (SubnetId)
      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            VolumeSize: 15 # in GB
      DisableApiTermination: false # this is the default
      ImageId: 'ami-0b0a60c0a2bd40612'
      InstanceInitiatedShutdownBehavior: 'stop'
      InstanceType: 't2.micro'
      KeyName: 'k8s-operations'
      Monitoring: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          PrivateIpAddress: '10.0.0.5'
          SubnetId: 'subnet-0525e7ef9499d1a5b' # TODO: extract to vars with appropriate AvailabilityZone
          DeviceIndex: '0'
          Description: 'Primary network interface'
          GroupSet:
            - 'sg-074c143d0f082afe6' # k8s-worker-internal (worker)
            - 'sg-0563033eb08ea547e' # k8s-worker-external (worker)
      Tags:
        - Key: node-type
          Value: compute
        - Key: Name
          Value: k8s-worker